name: Better Farmyard time

on: 
  workflow_dispatch:

jobs:
  manually-triggered:
    runs-on: ubuntu-latest
    steps:
      - name: My Action - Check the right branch
        uses: kardelio/branchcheck-gha@v1
        with:
          allowed_branch: "main"
      - name: Cowsays
        uses: mscoutermarsh/cowsays-action@v1
        with:
          text: "Hello staffs!"
