name: Something cool?

on: 
  issues:
    types: [opened]

jobs:
  print-issue:
    runs-on: ubuntu-latest
    steps:
      - name: "Display Message"
        run: |
          echo "New issue has been opened!"
          echo "The issue was titled: ${{ github.event.issue.title }}"
          echo "The author of the issue is: ${{ github.event.assignees }}"
